### ISSUE TITLE
submission file example

### ISSUE THREAD

**Issue by FuzhiYang** [Tsinghua-MARS-Lab/Online-HD-Map-Construction-CVPR2023#5]
Hi, 

I use the released ckpt to write a validation submission json file. Then I added json keys according to [submission format](https://github.com/Tsinghua-MARS-Lab/Online-HD-Map-Construction-CVPR2023/blob/master/resources/docs/metrics.md). Finally I submit this json file to val phase.

An error occured as below:

Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 500, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpdaalq2fx/compute/challenge_data/challenge_1954/main.py", line 67, in evaluate
    assert send_email(results['meta']), 'validation failed in send_email()'
AssertionError: validation failed in send_email()

I wonder what's wrong with my submission json file. Could you provide a toy submission file?

Best regards,
Fuzhi

**Comment by yuantianyuan01** [comment]
Sorry for the late response. We have fixed the bugs about submission. Please try with the latest version.
